### ISSUE TITLE
Fails when piping into expression with ::: (triple colon) operator

### ISSUE THREAD

**Issue by ctbrown** [tidyverse/magrittr#105]
I have failed to get magrittr to work when:
- suggested by a new package
- using testthat 
- when piping into an expression using a triple colon operator.

Like this:

```
"flags" %>% optigrab:::str_to_opts()  
```

It just didn't seem to pass CRAN's R checks though it worked find with `devtools` and earlier version of R.

Curious to know if there were other reports of this.

C-

**Comment by hadley** [comment]
Works ok for me:

``` r
library(magrittr)
"flags" %>% stringr:::str_to_upper()
#> [1] "FLAGS"
```

Created on 2018-07-02 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).
