### ISSUE TITLE
Question: Does a function know if it's being piped?

### ISSUE THREAD

**Issue by ateucher** [tidyverse/magrittr#127]
I'd like to be able to modify the return value of a function if (and only ever if) it is being piped into another function. Is this possible?

I'm guessing this is related to some of the discussion of lazy evaluation...

Thanks!

**Comment by gaborcsardi** [comment]
While it is technically possible, please don't do it. First, it would be hard to code up a solution that works for all future versions of magrittr.

Second, it is very bad practice to have different return values depending on context.

Write another function that just calls your original function, but it returns the different value, and use this second function in pipes.

**Comment by ateucher** [comment]
Thanks @gaborcsardi. 

I definitely agree with you with regards to your second point about different return values (which is why I only wanted to do it within a pipeline so that the user would never be exposed to this idiosyncrasy). But I concede that it is probably not a great road to go down and likewise too fragile.

What is your opinion on allowing a user to specify the output class via an argument?

**Comment by gaborcsardi** [comment]
> What is your opinion on allowing a user to specify the output class via an argument?

IMHO still not a good solution for *most cases*. I did this myself in the past, and came to regret it. It is much harder to think about functions that sometimes return this, sometimes that. I would probably just add another function, however trivial it is.

**Comment by smbache** [comment]
We do it in jqr and I think @sckott uses the same approach one more package too. There we want to know if a function call is the last in a chain.

**Comment by ateucher** [comment]
Thanks again @gaborcsardi and @smbache. I decided this would be a lot easier if I explained my use case/motivation. I opened an [issue](/ateucher/rmapshaper/issues/42) in my rmapshaper package to explain.
