### ISSUE TITLE
a new operator %g>% for ggplot?

### ISSUE THREAD

**Issue by jerryzhujian9** [tidyverse/magrittr#140]
it has been discussed here regarding plotting a ggplot object as a side effect:
http://stackoverflow.com/questions/27264266/multiple-ggplots-with-magrittr-tee-operator

Is this possible? Thanks a lot!

```
library(ggplot2)
library(dplyr)
library(magrittr)

# this one works
mtcars %T>%
  qplot(x = cyl, y = mpg, data = ., geom = "point") %>%
  qplot(x = mpg, y = cyl, data = ., geom = "point")

# so it may work also for ggplot like this?
mtcars %g>%
  {ggplot() + geom_point(aes(cyl, mpg))} %>%
  {ggplot() + geom_point(aes(mpg, cyl))}
```
guess %g>% has to be able to internally trigger a print() command in order to plot a ggplot object

**Comment by smbache** [comment]
I don't think magrittr should have any package-specific workarounds. 

Why not just use helpers, e.g. 
```R
qplotter <- function(data, ...) {
  print(qplot(data=data, ...))
  data
}
```

**Comment by hadley** [comment]
I think the real problem is that `print.ggplot()` doesn't invisibly return its first argument.

**Comment by smbache** [comment]
The above seems to indicate that it is the data they want back for successively producing several plots... but still you're right that `print.*` should return its argument.

**Comment by hadley** [comment]
There's also the problem with `+` vs `%>%` but that's out of scope.

**Comment by smbache** [comment]
Yeah, but one can always do `gg %>% + geom_*`; although not fantastic...
