### ISSUE TITLE
Piping a ggplot to a labelling function

### ISSUE THREAD

**Issue by jzadra** [tidyverse/magrittr#143]
See: [directlabels](https://github.com/tdhock/directlabels/issues/10#issuecomment-289139502) issue.

It seems that a ggplot cannot be piped to `directlabels`, and the author suggests that the problem is with how magrittr evaluates the piping sequence, rather than how directlabels accepts the ggplot.

**Comment by Yeedle** [comment]
This is not an issue with `directlabels` but with `ggplot` and `magrittr` in general. the change from `%>%` to `+` in ggplot means that you can directly pipe the output of a `ggplot` call to anything that expects a `ggplot` object as its first arg. 

p.s. a suggested alternative might be using https://github.com/thomasp85/pipeplotter

**Comment by hadley** [comment]
Yeah, this is an unfortunate consequence of ggplot2 being written prior to discovery of the pipe.

**Comment by smbache** [comment]
Since `%$%` uses `with` which is generic, something along the lines of 
```
with.gg <- function(g1, g2) g1 + g2
```
would allow you to use `%$%`.
