### ISSUE TITLE
feature request: pipe alias for `;` (and_then)

### ISSUE THREAD

**Issue by yeedle** [tidyverse/magrittr#144]
I would like to request an alias for `;`, useful for situations when functions with no output need to be run before a pipe. For example, a common operation might be:

```r
set.seed(42)
foo <- sample(...)
```

To make sure `set.seed` runs before the next line, one option is to put both statements on one line separated by a semicolon:

```r
set.seed(42); foo <- sample(...)
```

Not pretty, and diminishes code readability. A pipe alternative makes things nicer:

```r
foo <- set.seed(42) %and_then%
  sample(...)
```

**Comment by moodymudskipper** [comment]
You can do:

```
foo <- set.seed(42) %>%
  {sample(...)}
```

Or 

```
foo <- x %T>%         # x : first argument of sample
  {set.seed(42)} %>%
  sample(...)
```

**Comment by hadley** [comment]
Generally, we are moving towards a simpler magrittr, which means that we're not adding new aliases at this time.
