### ISSUE TITLE
`debug_fseq` fails when vectors of indices are provided

### ISSUE THREAD

**Issue by odeleongt** [tidyverse/magrittr#149]
As implemented, `debug_fseq` fails when providing vectors with length > 1 in `...` to specify which components to debug:

```
library(package = "magrittr")  
a <- . %>% cos %>% sin %>% tan  
debug_fseq(a, c(1, 3))
##Error in vapply(indices, is_valid_index, logical(1L)) : 
##  values must be length 1,
## but FUN(X[[1]]) result is length 2
```

This happens because `debug_fseq` collects indices from `...` with `list(...)`, thus getting elements with length > 1 when vectors with length > 1 are provided in the unmatched arguments (then `is_valid_index` returns logicals with length > 1 and `vapply` complains).

**Comment by hadley** [comment]
I think we're generally moving away from `debug_fseq()` and will be considering richer debug primitives.
