### ISSUE TITLE
peep pipe

### ISSUE THREAD

**Issue by romainfrancois** [tidyverse/magrittr#152]
Not sure how this would look like exactly but sometimes when a pipeline does not return what I wanted, I find myself doing some sort of bisect execution until I can spot the problem. 

Can we have something that would record the result of each step somewhere in a list, and move around it similar to what `recover` does ?

**Comment by smbache** [comment]
Hmm, I think it should not be in `%>%` (memory waste), and there are enough pipes already.
would it not be better to write a small collector:

```R
collector <- function() 
{
  collected <- list()
  function(.) 
  {
    if (missing(.)) {
      collected
    } else {
      collected[[length(collected) + 1]] <<- .
      .
    }
  }
}

collect <- collector()

foo <-
  iris %>% 
  head(10) %>% 
  collect %>% 
  transform(a = Sepal.Length/Sepal.Width) %>% 
  collect %>% 
  summary

# Call collect() to access the collected items.
collect()
```
These would also be easy to add where needed, comment in and out, and remove when not needed.

**Comment by romainfrancois** [comment]
I was thinking perhaps a dedicated pipe operator, to use as the first pipe, kind of like what `%<>%` does. The idea would be to have minimal work to do to turn this on

**Comment by hadley** [comment]
I think we'll have better ways to debug in the future, like @smbache I'm not enamoured with this approach.
