### ISSUE TITLE
Ceci n'est pas un*e* pipe

### ISSUE THREAD

**Issue by fcturner** [tidyverse/magrittr#153]
On different locations in the tidyverse packages I came across the French saying `Ceci n'est pas un pipe`, referring to the[ 1948 painting _La Trahison des images_](https://www.wikiart.org/en/rene-magritte/the-treachery-of-images-this-is-not-a-pipe-1948) by Rene Magritte.

Unfortunately, it should be **une pipe** and not **un pipe**. Now it's actually saying something very similar to `This is not an pipe`. Highly annoying for English speakers, as is `un pipe` for French speakers.

Since giving so much credit to Margritte (by even naming the package `magrittr`) I think it would be appropriate to fix the spelling.

Found on (quick search, it's also in some R help pages):
  - https://github.com/tidyverse/magrittr/blob/master/README.md
  - https://github.com/tidyverse/magrittr/blob/master/man/figures/logo.png

Logo `magrittr`:
![image](https://user-images.githubusercontent.com/7526559/28526364-a08430ec-7087-11e7-8f02-3e783477b253.png)
Painting by Margritte:
![image](https://user-images.githubusercontent.com/7526559/28526405-be541e0c-7087-11e7-9cc8-6e20bcaad334.png)

**Comment by tfjmp** [comment]
Actually un "pipe" is the pipe (pronounced the english way) used in software. Une pipe is the one you smoke. So `magrittr` feels correct.

**Comment by fcturner** [comment]
> un "pipe" is the pipe (pronounced the english way)

May be, but French speakers (and other  European French speakers like myself) pronounce `%>%` as ‘peep’ when talking about data analysis in French, not as ‘pipe’. To me it feels erroneous.

**Comment by tfjmp** [comment]
I am french too, never heard "peep".

**Comment by fcturner** [comment]
Then it’s just the PhD students in my study group (all doctors starting to learn R). I’ll let them know how you think about this. Thanks!

I rest my case :wink:
