### ISSUE TITLE
Piping into an expression that contains the $ sign fails

### ISSUE THREAD

**Issue by jeremyhoughton** [tidyverse/magrittr#156]
When you pipe into a function that is qualified with a $ sign, the function call fails.  This also has an impact on the modules package that uses the $ sign to expose the function from the module as documented [here](https://github.com/wahani/modules/issues/7).

Please see an example below:

```R
dummyData <- c(1:10)
MathList <- list()
MathList$medianWrapperMod <- function(data) {
  median(data)
}

# Fails with "Error in .$MathList : 3 arguments passed to '$' which requires 2"
dummyData %>%
  MathList$medianWrapperMod
```

**Comment by DragosMG** [comment]
I might be wrong, but this might be similar to the use case the [vignette]( https://cran.r-project.org/web/packages/magrittr/magrittr.pdf) references this on page 9. 

>  Another example where this is relevant is for reference class methods which are accessed using the $ operator, where one would do x %>% (rc$f), and not x %>% rc$f.

This works:
`dummyData %>%
    (MathList$medianWrapperMod)`

**Comment by hadley** [comment]
That's because 

```R
dummyData %>% MathList$medianWrapperMod
```

is translated to

```R
`$`(dummyData, MathList, medianWrapperMod)
```
