### ISSUE TITLE
magrittr::set_names and rlang/purrr::set_names are inconsistent

### ISSUE THREAD

**Issue by mmuurr** [tidyverse/magrittr#158]
`magrittr::set_names` conflicts with `rlang/purrr::set_names` in an incompatible way.
(The latter version requires only a single argument, using the first arg as the default for the second arg.)

Given the tight integration of `magrittr` in the tidyverse, should these inconsistencies be snuffed-out?

**Comment by smbache** [comment]
Yes. Magrittr aliases should be removed - and will be at some point.

**Comment by mmuurr** [comment]
Yay, thanks!

(In the meantime, my work-around is what I've dubbed the 'owl idiom', as it returns the same results in both cases: `%>% set_names(.,.)`.)

**Comment by hadley** [comment]
Part of #108
