### ISSUE TITLE
Would a %T$% operator make sense?

### ISSUE THREAD

**Issue by choisy** [tidyverse/magrittr#162]
I often find myself in a situation where a %T$% would be useful, where %T$% would be to %$% what %T>% is to %>%.
Has any of you ever considered developing such an operator?

**Comment by smbache** [comment]
Interesting. On the one hand it makes sense, on the other I'm cautious on adding too many new operators as there is always the risk of making things harder to read, or more confusing, and not gaining that much. I'll leave this open fr now.

**Comment by dgkf** [comment]
I recently found myself in a position to make use of this operator. The `%T$%` seemed like the clear analog to the `%T>%` operator and I was surprised that it didn't exist. I spent a good few minutes reading through the docs to see if it went by a different name.

Although I greatly appreciate the caution against going operator-overboard, I think that this operator is a clear composition of two operators already in the magrittr toolkit and also is a fairly unique combo of characters that I wouldn't expect to conflict with other namespaces.

**Comment by hadley** [comment]
I think it's now clear that magrittr will not gain new operators, but this is a great idea for another package 😄

**Comment by moodymudskipper** [comment]
You can design it with my package `mmpipe` :

```
# devtools::install_github("moodymudskipper/mmpipe")
library(mmpipe)
add_pipe(`%T$%`, substitute({local(with(., b));.}, list(b = body)))
iris %T$% {print(head(Species))} %>% head(2)
# [1] setosa setosa setosa setosa setosa setosa
# Levels: setosa versicolor virginica
#   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
# 1          5.1         3.5          1.4         0.2  setosa
# 2          4.9         3.0          1.4         0.2  setosa
```
