### ISSUE TITLE
Different behavior with pipe vs no pipe when `parent.frame()` is a default argument

### ISSUE THREAD

**Issue by wlandau** [tidyverse/magrittr#163]
I have a function that takes an environment as a secondary argument with default value `parent.frame()`. The value of `parent.frame()`, of course, changes depending on where it is evaluated, so I get a different environment when I use `%>%`. This turns out to generate unfortunate edge cases for [`drake`](https://github.com/ropensci/drake), particularly https://github.com/ropensci/drake/issues/335. This issue seems sufficiently different from #4, #146, and #159. cc @rkrug. 

```r
library(magrittr)
global <- 1
f <- function(x, env = parent.frame()) {
  force(env)
  print(ls(env))
}
# The following should agree, but do not.
f(1)
#> [1] "f"      "global"
1 %>% f
#> character(0)
```

From the `magrittr` documentation:

<blockquote>
Basic piping

- `x %>% f` is equivalent to `f(x)`
- `x %>% f(y)` is equivalent to `f(x, y)`
- `x %>% f %>% g %>% h` is equivalent to `h(g(f(x)))`

Here, "equivalent" is not technically exact: evaluation is non-standard, and the left-hand side is evaluated before passed on to the right-hand side expression. However, in most cases this has no practical implication.
</blockquote>

It seems like the call `h(g(f(x)))` could easily be constructed from the call `x %>% f %>% g %>% h` before any evaluation (static code analysis only). This approach might have also made `x %>% f %>% g %>% h` run just as fast as `h(g(f(x)))` (re: #15 and #16). To what extent was this approach part of the original design?

**Comment by hadley** [comment]
The downside of converting `. %>% f %>% g` to `function(.) f(g(.))` is that tracebacks are hard to understand. (They're hard to understand in the released version, but they will be much better in the next release).

**Comment by smbache** [comment]
And that left-hand sides might be used several places in the corresponding right-hand side. You’d want to only evaluate the lhs once.

**Comment by hadley** [comment]
And now see <https://github.com/tidyverse/magrittr/blob/master/vignettes/tradeoffs.Rmd> for a fuller exposition of the various tradeoffs.

**Comment by wlandau** [comment]
Thanks, your comments and the vignette are very helpful. I was not considering single evaluation, and I did not know the lazy pipe had a shorter call stack.

I know the vignette says it is intended mostly for developers, but may I suggest briefly defining `%<~%`? Personally, I have only seen it in `future`.

**Comment by hadley** [comment]
It is defined later in the doc.
