### ISSUE TITLE
function chaining without data input

### ISSUE THREAD

**Issue by gdkrmr** [tidyverse/magrittr#166]
It would be great if chained function without data input would return a function, e.g.

```R
f %>% g
```
should be equal to
```R
function(x) g(f(x))
```

then syntax of `lapply` calls and such can be made much simpler and more concise, e.g.
```R
lapply(data, f %>% g)
```
or even better 
```R
f %>% g %>% lapply(data, .)
```
instead of
```R
lapply(data, function (x) g(f(x)))
```

**Comment by smbache** [comment]
```
foo <- . %>% bar %>% baz
```

**Comment by gdkrmr** [comment]
cool, thanks, did I miss this in the manual?

**Comment by smbache** [comment]
Possibly 😊
