### ISSUE TITLE
Things like `%<T>%` possible?

### ISSUE THREAD

**Issue by MajoroMask** [tidyverse/magrittr#176]
Is there any change that we can get a pipe operator which combines the function of `%<>%` and `%T>%`? We can use it like this:

`output_dir  %<T>% dir.create() %>% normalizePath()`

which is the same as: 

`output_dir <- output_dir %T>% dir.create() %>% normalizePath()`

See? Could be a little easier. 
Just a thought, may not be mature.:sparkles: Thanks for watching.

**Comment by hadley** [comment]
The trajectory for magrittr is trying to get simpler over time, not more complicated. I don't think we want to have a pipe for every combination of other pipes.
