### ISSUE TITLE
error when loading magrittr

### ISSUE THREAD

**Issue by emankhalaf** [tidyverse/magrittr#177]
Hello,
I just installed magrittr using the following code:
devtools::install_github("tidyverse/magrittr")

the package was installed successfully, but when loaded I got this error:

Error in value[[3L]](cond) : Package ‘magrittr’ version 1.5 cannot be unloaded: Error in unloadNamespace(package) : namespace ‘magrittr’ is imported by ‘dplyr’, ‘igraph’, ‘stringr’, ‘forcats’, ‘tidyverse’, ‘purrr’, ‘rvest’, ‘modelr’, ‘tidyr’ so cannot be unloaded

May you please help me to figure it out?
Thanks

**Comment by hadley** [comment]
I think you just need to restart R.
