### ISSUE TITLE
Suggestion: change pipe-operator names for consistency and clarity

### ISSUE THREAD

**Issue by prosoitos** [tidyverse/magrittr#178]
I love magrittr and am teaching the less common pipe-operators in workshops to encourage their use. I find that their long and inconsistent names is not helping students however, and even people who regularly use them never remember their names and have to describe their symbols when referring to them orally. Short and consistent names would (I think) be easier and neater.

Here are the current names:

```
magrittr forward-pipe operator (note the inconsistent hyphen position)
magrittr compound assignment pipe-operator
magrittr exposition pipe-operator
magrittr tee operator (what happened to the "pipe"?)
```
I suggest replacing these names with the following:

```
assignment pipe
compound assignment pipe
exposition pipe
tee pipe
```
I would be happy to submit a PR if you agree with the change.

**Comment by prosoitos** [comment]
I thought the last one was `%T%`, but it is in fact `%T>%`. So `tee assignment pipe` might be more appropriate?

**Comment by smbache** [comment]
why "assignment"? Nothing is being assigned by any pipe other than `%<>%`.

**Comment by prosoitos** [comment]
OK. I see what you mean.

From the term `compound assignment`, I had understood that you were considering the process of piping as a form of assignment (as in: pipe from lhs to rhs, then re-pipe to lhs). So I understood `compound assignment` as "double assignment".

But I now see that the term `compound assignment` rather meant "pipe and assign".

I *just* submitted a PR. But I am happy to update all the names to whatever everybody think is best.

**Comment by prosoitos** [comment]
Maybe??

```
pipe
assignment pipe
exposition pipe
tee pipe
```

**Comment by smbache** [comment]
“Compound assignment” is the term normally used for this type of functionality, eg `+=` and friends.

**Comment by prosoitos** [comment]
OK. Without a background in any other language, I didn't know. Thanks for clarifying. The `<` and `>` symbols in `$<>$` also confused me in my interpretation of the vocabulary use since I didn't know better and since it is the same symbol (in one direction or the other) while they mean different things (piping with `>` and then assigning back with `<`).

But it now makes sense and I am happy to update the names to whatever seems best.
