### ISSUE TITLE
magrittr does not work with sprintf properly?

### ISSUE THREAD

**Issue by jerryzhujian9** [tidyverse/magrittr#184]
Hi,
I wrote a pipe combing with sprintf.  The first command does not work as expected, but the second can.  Is there something I did wrong or something I should know about magrittr in this particular case?

```
c("col1",'col3') %>% sprintf('There are %s', paste0(.,collapse=','))  # gets a vector

c("col1",'col3') %>% paste0(.,collapse=',') %>% sprintf('There are %s', .)
```

**Comment by hadley** [comment]
The first is equivalent to:

```R
c("col1",'col3') %>% sprintf(., 'There are %s', paste0(.,collapse=',')) 
```
