### ISSUE TITLE
"pas une pipe" instead of "un pipe"

### ISSUE THREAD

**Issue by SimonHeuberger** [tidyverse/magrittr#203]
Completely irrelevant of the functionality of the awesome package, but I noticed it the other day: Shouldn't it be "Ceci n'est pas une pipe" instead of "un pipe", since that's the original from Magritte (see attached)? Or am I missing something?
![MagrittePipe](https://user-images.githubusercontent.com/17678051/71689862-167bfc00-2d71-11ea-9321-2be934da320d.jpg)

**Comment by smbache** [comment]
You missed that a computer pipe is masculine and hence it should be “in” :)

**Comment by SimonHeuberger** [comment]
I knew there was something, cheers!
