### ISSUE TITLE
Typo in split_chain.R

### ISSUE THREAD

**Issue by bdhumb** [tidyverse/magrittr#205]
There is a typo here where it says myst instead of must. I don't particularly want to figure out how to update it myself and get it merged in but maybe someone who contributes has 1 minute to fix it?

<img width="431" alt="Screenshot" src="https://user-images.githubusercontent.com/140095/73142619-fd9f0600-40e4-11ea-89cb-683aa396b487.PNG">

**Comment by Bisaloo** [comment]
@bdhumb, I just had a look and this has actually been fixed in https://github.com/tidyverse/magrittr/commit/e95aa63960e6926b701d0fe927587bacccb53f0f (5 years ago). There just hasn't been a release on CRAN since then.
