### ISSUE TITLE
Dot forced by `{...}` anonymous function

### ISSUE THREAD

**Issue by egnha** [tidyverse/magrittr#224]
According to NEWS.md, as of 1.5.0.9000 `%>%` won't force the LHS.

Example from NEWS.md:
```r
ignore <- function(x) "return value"
stop("never called") %>% ignore()
#> [1] "return value"
```
However, the equivalent expression using `{...}` forces the LHS:
```r
stop("never called") %>% {"return value"}
#> Error in stop("never called") %>% { : never called
```
Is this the expected behavior? (Or have I misunderstood the semantics of `{...}`?)

**Comment by hadley** [comment]
You can see what's happening if you remove the pipe:

``` r
ignore <- function(x) "return value"
ignore(stop("never called"))
#> [1] "return value"

{
 stop("never called")
 "return value"
}
#> Error in eval(expr, envir, enclos): never called
```

<sup>Created on 2020-09-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by egnha** [comment]
Perhaps it would then be helpful to document the fact that `x %>% {...}` forces `x`. (Or put differently, that `x %>% {...}` and `x %>% (function(.) ...)` are not strictly equivalent.)

**Comment by hadley** [comment]
That fact is sufficiently esoteric that I'm not sure including it in the documentation would help anyone.
