### ISSUE TITLE
object ‘%T>%’ is not exported by 'namespace:magrittr'

### ISSUE THREAD

**Issue by hackereye** [tidyverse/magrittr#228]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](https://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

Brief description of the problem

```r
# insert reprex here
```

**Comment by lionel-** [comment]
When does this happen? What is your `sessionInfo()`? Have you tried reinstalling magrittr?

**Comment by lionel-** [comment]
Sorry we can't help you without more information. Please let us know if you still have the problem.
