### ISSUE TITLE
Feature request: shortcut `%<>%`

### ISSUE THREAD

**Issue by IsadoraBM** [tidyverse/magrittr#237]
Impossible to get help from kevinushey through addinsexamples on modifying the existing `%in%` so I'm appealing to you for compound pipe `%<>%` hotkey shortcut.  Wish I had requested before 2.0 but maybe you'll make an update?

---

Can't add hotkey for `%<>%`

```r
# General coding knowhow 404
```

**Comment by lionel-** [comment]
Sorry I don't know anything about RStudio addins but I don't think this is the right place to request this feature?
