### ISSUE TITLE
Why does magrittr export extract as "[" ?

### ISSUE THREAD

**Issue by torbjorn** [tidyverse/magrittr#246]
Why does magrittr export `extract`as 

    > magrittr::extract
    .Primitive("[")

When tidyr exports it as:

    > tidyr::extract
    function (data, col, into, regex = "([[:alnum:]]+)", remove = TRUE, 
        convert = FALSE, ...) 
    {
        ellipsis::check_dots_used()
        UseMethod("extract")
    }

This will for sure cause ugly breakage when you accidentally load these packages in the wrong order (just happened to me)

**Comment by lionel-** [comment]
magrittr and tidyr were designed separately. In general, the tidyverse reexports `%>%` so you don't have to `library(magrittr)`. If you want attach the package, you'll need to manage the exports.

**Comment by torbjorn** [comment]
Sorry, hope I can discuss briefly without reopening this as an issue;

Just checked the git log of both projects. Are you saying that tidyr caused this problem when they created the extract verb in june 2014, seeing as you had already created the extract export february 2014?

**Comment by lionel-** [comment]
Yes, some of the functions exported in magrittr have high-value names. This increases the chance of conflicts with other packages, including some attached by `library(tidyverse)`.
