### ISSUE TITLE
Magrittr Logo

### ISSUE THREAD

**Issue by bsurial** [tidyverse/magrittr#260]
I realized today when teaching R and the pipe operator that the magrittr logo has an error. Unless I am missing something, it should say "ceci n'est pas une pipe" as pipe is feminin. 

See also: [https://de.wikipedia.org/wiki/La_trahison_des_images](https://de.wikipedia.org/wiki/La_trahison_des_images)

**Comment by lionel-** [comment]
See https://magrittr.tidyverse.org/reference/faq-pipe-gender.html :)
