### ISSUE TITLE
difference in performance

### ISSUE THREAD

**Issue by ggrothendieck** [tidyverse/magrittr#261]
Could you comment on 

https://stackoverflow.com/questions/74841437/huge-processing-speed-difference-in-running-apparently-similar-codes-resulted

which appears to have found a situation where the magrittr pipe is materially lsow4r than the native pipe.

**Comment by lionel-** [comment]
> lsow4r

?

**Comment by lionel-** [comment]
There is no reprex in this post but on a first glance I think Andrew Gustar's comments provide the explanation.
