### ISSUE TITLE
Pipe doesn't work in basic round function

### ISSUE THREAD

**Issue by Yann-C-INN** [tidyverse/magrittr#266]
<img width="137" alt="image" src="https://github.com/tidyverse/magrittr/assets/130037694/1bcfb359-3ebe-4f9d-96f8-495eac81ff5e">

Hey guys.
I think this should really work, as part of the tidy approach using pipes:
No reason that this
`(2054-2000)/2000 %>% round(2)`
`[1] 0.027`
Won't be the same as this
`round(0.027,2)`
`[1] 0.03`

**Comment by lionel-** [comment]
Hello, rewriting the operator precedence rules is out of scope for magrittr, so you'll have to use explicit parentheses. Note that this is also the case with the base `|>` pipe.
