### ISSUE TITLE
Question: UN or UNE pipe?

### ISSUE THREAD

**Issue by prostkopio** [tidyverse/magrittr#268]
I don't know French and as a matter of fact I should have been writing my PhD thesis right now but I can't help noticing that in the package logo and description there is 'Ceci n'est pas **un** pipe' included instead of 'Ceci n'est pas **une** pipe'. 
Is this a bug or both forms are allowed?

**Comment by lionel-** [comment]
Hello, see https://magrittr.tidyverse.org/reference/faq-pipe-gender.html
