### ISSUE TITLE
Question: defining a pipe operator with equivalent behavior to `%>% {...}`

### ISSUE THREAD

**Issue by ramiromagno** [tidyverse/magrittr#272]
Hi!

I know that if the placeholder is only used in a nested function call, the lhs is also placed as the first argument, and we can override this by wrapping the rhs in braces. However, I'm wondering if there's a straightforward way, using magrittr's exported functions, to create a new pipe operator that allows multiple placements but never places the lhs as the first argument.

In other words, would it be easy to define a new pipe, say `%>>%`, that makes these two commands equivalent?

```R
1:10 %>% {c(min(.), max(.))}
```

```R
1:10 %>>% c(min(.), max(.))
```

I'm not suggesting that this functionality should be included in magrittr, as I understand the current design choices are deliberate. I'm just asking if I wanted this functionality in my own code, would it be straightforward to implement using one of the exported functions from magrittr?

Thanks!

**Comment by lionel-** [comment]
Untested but try something along the lines of:

```r
`%>>% <- function(data, expr) {
  eval(substitute(expr), list(. = data), parent.frame())
}
```

**Comment by ramiromagno** [comment]
Thank you Lionel! This is neat and effective!
