### ISSUE TITLE
Calling return() from a pipe

### ISSUE THREAD

**Issue by gaborcsardi** [tidyverse/magrittr#32]
I guess this cannot be implemented, but maybe I am missing something:

``` r
f <- function() {
   "this is the pipe" %>% return()
   "no, it is not"
}
f()
# [1] "no, it is not"
```

**Comment by dykim22** [comment]
I have the same issue here. I think, at least, we need to raise an exception when there comes `return()` for the right hand side of the function`%>%`. 

`f <- function() {if (TRUE) 'Success' %>% return()`

**Comment by dykim22** [comment]
I have the same issue here. I think, at least, we need to raise an exception when there comes `return()` for the right hand side of the function`%>%`. 

It causes some critical issue when `%>% return()` combination is used inside the if-statement for the purpose of 'returning early from a function'.

Here is an example.

```R
f <- function() {
  if (TRUE) {
    'Success' %>% return()
  }

  'This line must not be run.'
}

# [1] This line must not be run.
```

**Comment by YulongNiu** [comment]
@dy-kim I have a same problem. Vote for an exception when `return()` is on the right hand of `%>%`.

**Comment by hadley** [comment]
This will work in the simplified branch (which is where future development is going) because 

```R
"this is the pipe" %>% return()
```

Is translated to

```R
(function(.) {
  return(.)
})("this is the pipe")
```

**Comment by stevecondylios** [comment]
The issue [got me](https://stackoverflow.com/questions/59596950/strange-behaviour-when-piping-to-return-in-r-function) today too. Easy to avoid once known, but a 'gotcha' for anyone unaware of it. 

Possibly un/related: [piping to `ls()`](https://stackoverflow.com/questions/57398452/unexpected-behaviour-when-piping-to-ls-in-r) also seems to behave somewhat unexpectedly.

**Comment by mmuurr** [comment]
I was also just recently bitten by this unexpected (though understandable, after reading the above) behavior. Will magrittr 2.0 support this behavior? (I suppose some of the answer depends a bit on the implementation complexity, which is nicely laid out in [this doc](https://magrittr.tidyverse.org/articles/tradeoffs.html).)

The pattern mentioned above (conditional early-returns) is quite nice to write with pipes. And like the comments above, I think some explicit documentation on when to _not_ use them would be helpful ... perhaps that can be opened as a separate issue?

**Comment by lionel-** [comment]
Unfortunately we can't make this behaviour work while simultaneously supporting multiple placeholders, laziness, and persistent piped values. Using `return()` in a pipe becomes an error in magrittr 2.0.

For backward compatibility we support piping into a trailing return call, but note that it will only return from the pipe, not the enclosing function as would be expected.

**Comment by mmuurr** [comment]
The silent behavior now is sneaky/confusing, so I think having it (and any other known non-supported functions) simply raise an error in magrittr 2.0 will be a great addition, thanks!

**Comment by karchern** [comment]
Magrittr's current version is 2.0.3 but I just (silently) ran into this. I find this highly problematic given how piping in R is typically taught (which is that `object %>% function()` is literally equivalent to `function(object)`) and think it would be amazing if this would at least throw a warning.
