### ISSUE TITLE
A function to invoke functions

### ISSUE THREAD

**Issue by wch** [tidyverse/magrittr#37]
For example, something like:

``` R
invoke <- function(f, ...) f(...)
```

This would be useful for pipelines when one of the functions returns a function:

``` R
create_adder <- function(value) {
  function(x) x + value
}

1+1 %>% create_adder() %>% invoke(3)
# [1] 5
```

**Comment by hadley** [comment]
See now `purrr::invoke()` and eventually [`purrr::exec()`](https://github.com/tidyverse/purrr/issues/437)
