### ISSUE TITLE
Functions with envir = parent.frame()

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/magrittr#38]
Compare the following two statements:

```
"file.rda" %>% load
load("file.rda")
```

The former will load the data into a temporary environment; the reason is that `load` is declared as

```
load <- function (file, envir = parent.frame(), verbose = FALSE)
```

The same happens with `assign` and `get`.

This is at least unexpected, I'm not sure if we should call it a bug. Worse, I'm not sure if this issue can be solved at all in a robust way.

Similar to #32.

**Comment by hadley** [comment]
I think the best we can do is to provide a convenient way to get the right environment, i.e. #171.

I'm now almost certain that that's no way to implement the pipe that would preserve `parent.frame()`, without sacrificing properties that we care about more.

**Comment by iago-pssjd** [comment]
I've just found another problem with the `save` function, which is `envir = parent.frame()` too, which seems to be related to this issue.

If I save a data frame with pipe:
```
library(magrittr)
mtcars %>% save(file = "test.rdata")
```
And later, when I don't have it in the Global Env, I try to load with
```
load("test.rdata")
```
it does not load anything. If I save it without pipe, all works as usual.
