### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/magrittr#43]
Not saving intermediate result also means... not saving intermediate results. When creating longish pipes (10 steps or so), testing the pipe always means executing all steps. This slows down development.

How about providing, for interactive mode, some kind of caching functionality. The value of a `%>%` call could be reused if both the LHS (hash? address?) and the RHS (parse tree equality? string equality?) haven't changed. If values are taken from the cache, a message could indicate this. Of course, there also should be an easy way to invalidate the cache.

In a preliminary test, inserting `R.cache::evalWithMemoization` into the pipe didn't work due to eager evaluation of the pipe. Still, the functionality in `R.cache` could be helpful here.

**Comment by holstius** [comment]
Eager evaluation of `lhs` tripped me up too. With a suitable implementation of a helper function `cached <- function(expr, ...)` I used to write:

    foo <- 
      cached({
        some_tbl %>%
        compute_stuff %>% 
        summarize_nicely
      }, "foo.rds")

... and thought instead I could express the intention as:

    foo <- 
      some_tbl %>%
      compute_stuff %>% 
      summarize_nicely %>%
      cached("foo.rds")

... or, with some modifications, up front:

    foo <- 
      # ???
      compute_stuff %>% 
      summarize_nicely

... but I couldn't figure out where there was an opportunity to short-circuit the evaluation.

**Comment by hadley** [comment]
I think this should probably go in another package. If we had a lazy pipe (#120) it would be easy to do elsewhere.
