### ISSUE TITLE
Problem when using missing() together with pipes

### ISSUE THREAD

**Issue by gforge** [tidyverse/magrittr#59]
I just stumbled upon odd error due to `missing()` when implementing magrittr pipes in my package, below is an example that illustrates the odd error:

``` r
fa <- function(a, b){
  a %>% 
    fb(b=b)
}
fb <- function(a, b){
  if(missing(b)){
    print("missing")
  }else{
    print(b)
  }
}

fa(a=1)
```

Throws: `Error in print(b) : argument "b" is missing, with no default` 

PS. Thank you for this excellent package - I'm excited as a kid on X-mas...

**Comment by daattali** [comment]
Just want to upvote this thread - I'm also commonly running into this problem and have to use regular ugly verbose pipelines instead of magrittr when I'm dealing with missing arguments

**Comment by Hong-Revo** [comment]
Have there been any developments on this? I'm running into issues where missing args can break my pipeline.

**Comment by hadley** [comment]
I think this is a general problem with using missing. Just default to `NULL` then check with `is.null()`.  I think that's generally better design, anyway, because it makes it more clear which arguments are required and which are optional.
